package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// AgentPolicySpec defines the desired state of AgentPolicy.
type AgentPolicySpec struct {
	// AgentSelector selects the AgentCards this policy applies to.
	AgentSelector AgentSelector `json:"agentSelector"`

	// Ingress defines the ingress access control policy.
	// +optional
	Ingress *IngressPolicy `json:"ingress,omitempty"`

	// MCPTools references the MCP tools virtual server for this policy.
	// +optional
	MCPTools *MCPToolsRef `json:"mcpTools,omitempty"`

	// Agents is a list of agent names that this policy applies to.
	// +optional
	Agents []string `json:"agents,omitempty"`

	// External defines the policy for external service access and credential management.
	// +optional
	External *ExternalPolicy `json:"external,omitempty"`

	// RateLimit defines rate limiting parameters for this policy.
	// +optional
	RateLimit *RateLimitSpec `json:"rateLimit,omitempty"`
}

// AgentSelector defines how to select AgentCards by label matching.
type AgentSelector struct {
	// MatchLabels is a map of key-value pairs used to match AgentCards.
	MatchLabels map[string]string `json:"matchLabels"`
}

// IngressPolicy defines which agents and users are allowed to access the selected agents.
type IngressPolicy struct {
	// AllowedAgents is a list of agent names permitted to communicate with the selected agents.
	AllowedAgents []string `json:"allowedAgents,omitempty"`

	// AllowedUsers is a list of user identifiers permitted to communicate with the selected agents.
	AllowedUsers []string `json:"allowedUsers,omitempty"`
}

// MCPToolsRef references an MCP tools VirtualServer.
type MCPToolsRef struct {
	// VirtualServerRef is the name of the VirtualServer resource for MCP tools.
	VirtualServerRef string `json:"virtualServerRef"`
}

// ExternalPolicy defines how the agent accesses external services and manages credentials.
type ExternalPolicy struct {
	// Rules defines per-host external access rules.
	Rules []ExternalRule `json:"rules"`

	// DefaultMode is the default credential handling mode applied when no rule matches.
	// +kubebuilder:validation:Enum=vault;exchange;passthrough;deny
	// +kubebuilder:default=deny
	DefaultMode string `json:"defaultMode"`
}

// ExternalRule defines the credential handling policy for a specific external host.
type ExternalRule struct {
	// Host is the external hostname this rule applies to.
	Host string `json:"host"`

	// Mode is the credential handling mode for this host.
	// +kubebuilder:validation:Enum=vault;exchange;passthrough;deny
	Mode string `json:"mode"`

	// VaultPath is the path in a vault where credentials for this host are stored.
	// +optional
	VaultPath string `json:"vaultPath,omitempty"`

	// Audience is the intended audience for token exchange.
	// +optional
	Audience string `json:"audience,omitempty"`

	// Scopes is the list of OAuth scopes to request during token exchange.
	// +optional
	Scopes []string `json:"scopes,omitempty"`

	// Header is the HTTP header name used to inject the credential.
	// +optional
	// +kubebuilder:default=Authorization
	Header string `json:"header,omitempty"`

	// HeaderPrefix is the prefix prepended to the credential value in the header.
	// +optional
	// +kubebuilder:default="Bearer "
	HeaderPrefix string `json:"headerPrefix,omitempty"`
}

// RateLimitSpec defines rate limiting configuration.
type RateLimitSpec struct {
	// RequestsPerMinute is the maximum number of requests allowed per minute.
	// +kubebuilder:validation:Minimum=1
	RequestsPerMinute int `json:"requestsPerMinute"`
}

// AgentPolicyStatus defines the observed state of AgentPolicy.
type AgentPolicyStatus struct {
	// Conditions represent the latest available observations of the AgentPolicy's state.
	// +listType=map
	// +listMapKey=type
	Conditions []metav1.Condition `json:"conditions,omitempty"`

	// MatchedAgentCards is the number of AgentCards matched by the selector.
	MatchedAgentCards int `json:"matchedAgentCards,omitempty"`

	// GeneratedResources lists the Kubernetes resources generated by this policy.
	GeneratedResources []GeneratedResourceRef `json:"generatedResources,omitempty"`
}

// GeneratedResourceRef is a reference to a Kubernetes resource generated by the controller.
type GeneratedResourceRef struct {
	// Kind is the Kubernetes resource kind.
	Kind string `json:"kind"`

	// Name is the name of the generated resource.
	Name string `json:"name"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:resource:shortName=ap
// +kubebuilder:printcolumn:name="Matched",type=integer,JSONPath=`.status.matchedAgentCards`
// +kubebuilder:printcolumn:name="Ready",type=string,JSONPath=`.status.conditions[?(@.type=="Ready")].status`
// +kubebuilder:printcolumn:name="Age",type=date,JSONPath=`.metadata.creationTimestamp`

// AgentPolicy is the Schema for the agentpolicies API.
type AgentPolicy struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   AgentPolicySpec   `json:"spec,omitempty"`
	Status AgentPolicyStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// AgentPolicyList contains a list of AgentPolicy.
type AgentPolicyList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []AgentPolicy `json:"items"`
}

func init() {
	SchemeBuilder.Register(&AgentPolicy{}, &AgentPolicyList{})
}
